name: 'Generate Blog'
description: 'Generate by hexo blog.'
runs:
  using: "composite"
  steps:
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: "18"
        
    - name: Cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache
        restore-keys: |
          ${{ runner.OS }}-npm-cache
          
    - name: Fix File Modify Time
      shell: bash
      run: git ls-files -z | while read -d '' path; do touch -d "$(git log -1 --format="@%ct" "$path")" "$path"; done
      
    - name: Install Node Dependencies
      shell: bash
      run: npm install
      
    - name: Install Pandoc
      shell: bash
      run: |
        wget https://github.com/jgm/pandoc/releases/download/2.19.2/pandoc-2.19.2-1-amd64.deb -O pandoc.deb
        sudo dpkg -i pandoc.deb
        pandoc -v
        
    - name: Build
      shell: bash
      run: npm run build